---
Name: minifyhtml
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        MinifyHTMLMiddleware: '%$Innoweb\MinifyHTML\Middleware\MinifyHTMLMiddleware'
